---
title: "03"
format: html
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(adventdrob)
library(tictoc)
library(gganimate)
```


## Part 1


```{r}
input <- "..@@.@@@@.
@@@.@.@.@@
@@@@@.@.@@
@.@@@@..@.
@@.@@@@.@@
.@@@@@@@.@
.@.@.@.@@@
@.@@@.@@@@
.@@@@@@@@.
@.@.@@@.@."

rolls <- tibble(r = read_lines(input))
rolls <- tibble(r = read_lines("input/04"))
rolls
```


```{r}
grid_tidy(rolls, r) |> 
  adventdrob::adjacent_join(diagonal = TRUE) |> 
  mutate(roll = if_else(value2 == "@", 1L, 0L)) |> 
  summarise(sum_roll = sum(roll), .by = c(row, value, col)) |> 
  filter(value == "@", sum_roll < 4)
```

## Part 2


```{r}
grid_tidy(rolls, r) |> 
  adventdrob::adjacent_join(diagonal = TRUE) |> 
  mutate(roll = if_else(value2 == "@", 1L, 0L),
         val = value) -> troll # tibble roll!
  
  
forkable_roll <- function(tib) {
  tib |> 
    summarise(sum_roll = sum(roll), .by = c(row, value, col)) |> 
    filter(value == "@", sum_roll < 4) |> 
    nrow()
}

remove_roll <- function(tib) {
  tib |> 
    mutate(sum_roll = sum(roll), .by = c(row, value, col),
           val = value) |> 
    mutate(value = if_else(value == "@" & sum_roll < 4, '.', value),
           val = if_else(val != value, "O", val)) |> 
    distinct(row, value, col, val) |> 
     adventdrob::adjacent_join(diagonal = TRUE) |> 
    mutate(roll = if_else(value2 == "@", 1L, 0L))
}

fr <- forkable_roll(troll)
n_run <- 1L
anitroll <- mutate(troll, run = n_run)
removed <- fr
tic()
while (fr > 0) {
  troll <- remove_roll(troll)
  fr <- forkable_roll(troll)
  removed <- append(removed, fr)
  #message(paste("fr: ", fr))
  n_run <- n_run + 1L
  anitroll <- bind_rows(anitroll,
                        mutate(troll, run = n_run)
  )
}
sum(removed)
toc()
```



6.344 secs 8538

Animation (previous takes 10.9 seconds with `anitroll`)

```{r}

count(anitroll, val)

distinct(anitroll, row, val, col, run) |> 
  ggplot(aes(x = row, y = col, fill = val)) +
  geom_tile() +
  transition_states(states = run, state_length = 2) +
  scale_fill_manual(values = c("grey90",  "gold", "orange")) +
  theme_void(18) +
  coord_fixed() + 
  labs(title = "{closest_state}",
       fill = NULL) -> p
animate(p)
anim_save("d04_2025.gif")
```

