---
title: "05"
format: html
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(adventdrob)
library(tictoc)
library(GenomicRanges)

options(scipen = 999)
```


## Part 1

```{r}
input <- "3-5
10-14
16-20
12-18

1
5
8
11
17
32"

ingredients <- read_lines(input)
ingredients <- read_lines("input/05")
idx_split <- which(ingredients == "")
ingredients_ids <- tibble(end = ingredients[(idx_split + 1L):length(ingredients)] |> as.double(),
                          start = end - 1,
                          strand = '+',
                          seqnames = "chr1")
freshs <- tibble(inter = ingredients[seq_len(idx_split - 1L)]) |> 
  separate_wider_delim(cols = inter, delim = '-', names = c("start", "end")) |> 
  mutate(start = as.double(start) -1,
         end = as.double(end),
         strand = '+',
         seqnames = "chr1")
# freshs |> 
#   select(seqnames, start, end) |> 
#   write_tsv("freshs.bed", col_names = FALSE)
# 
# ingredients_ids |> 
#   select(seqnames, start, end) |> 
#   write_tsv("ingredients_ids.bed", col_names = FALSE)
```

Convert to Genomic Ranges, does not work with int32

```{r}
freshs_gr <- makeGRangesFromDataFrame(freshs)
ingredients_ids_gr <- makeGRangesFromDataFrame(ingredients_ids)

subsetByOverlaps(ingredients_ids_gr, freshs_gr)
```


```{r}
is_fresh <- function(i, tib) {
  tib |> 
    mutate(i = i,
           fresh = between(i, start + 1, end)) |> 
    summarise(any(fresh)) |> 
    pull()
}
tic()
ingredients_ids |> 
  select(end) |> 
  mutate(intervals = list(select(freshs, start, end)),
         is_fresh = map2_lgl(end, intervals, is_fresh)) |> 
  summarise(sum(is_fresh))
toc()
```

607 in 1.2 sec


## Part 2

```{r}
freshs <- mutate(freshs, start = start + 1) 


tic()
# great solution by tinygreen https://stackoverflow.com/a/73507369/1395352
library(data.table)
setDT(freshs)
freshs[
  order(start),
  # .N reports nb of obs per group
  .(start = min(start), end = max(end), n = .N),
  by = .(group = cumsum(start > cummax(shift(end, fill = -Inf))))
][,
  # .() is an alias for list() to keep the data.table structure
  .(group, nobs = n, start, end, range = end - start + 1)
][,
  sum(range) # no .() to obtain a vector
]
toc()
```

342433357243918 in 0.028 sec

dplyr version:

```{r}
tic()
freshs |> 
  arrange(start) |> 
  # to understand it
  # 0. must be sorted in ascending order
  # 1. lag for comparison between start and previous end
  # 2. cummax(reports the max value observed)
  # 3. cumsum create groups by summing booleans
  # 4. per group we take smallest and highest values
  mutate(lag = lag(end, default = first(end)),
         cummax = cummax(lag),
         cummaxstart = cummax < start,
         cums = cumsum(cummaxstart)) |> 
  # group_by necessary because takes an expression
  group_by(group = cumsum(cummax(lag(end, default = first(end))) < start)) |> 
  summarise(start = min(start), end = max(end)) |> 
  mutate(range = end - start + 1) |> 
  summarise(sum(range))
toc()
```


