---
title: "06"
format: html
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(tictoc)
options(scipen = 999)
```


## Part 1


```{r}
input <- "123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   + "

input <- "input/06"

n_lines <- read_table(input, col_names = FALSE, show_col_types = FALSE) |> nrow()
mpoulpe <- read_table(input, col_names = FALSE, show_col_types = FALSE, n_max = n_lines - 1L) |> 
  select(where(is.double))
operations <- read_table(input, col_names = FALSE, show_col_types = FALSE, skip = nrow(mpoulpe))|> 
  select(where(is.character))
```


```{r}
tic()
imap_dbl(mpoulpe, \(i, j) reduce(i, get(operations[[j]]))) |> 
  reduce(`+`)
toc()
```

7326876294741
0.031 sec elapsed

## Part 2

```{r}

read_lines(input)[-n_lines] |> 
  map(str_split_1, '') |> 
  enframe(value = "v") |> 
  unnest_wider(v, names_sep = '_') |> 
  select(-name) |> 
  map(\(x) paste0(x, collapse = '') |> as.numeric()) -> rpoulpe

right_left <- vector(mode = "list", length = length(operations))
i <- 1L

for (ri in seq_along(rpoulpe)) {
  if (is.na(rpoulpe[[ri]])) {
    i <- i + 1L
    next
  }
  #message(paste("ri ", ri, " i ", i, " ", rpoulpe[[ri]]))
  right_left[[i]] <- append(right_left[[i]], rpoulpe[[ri]])
}

imap_dbl(right_left, \(i, j) reduce(i, get(operations[[j]]))) |> 
  reduce(`+`)
```

10756006415204


