---
title: "07"
format: html
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(adventdrob)
library(tictoc)
options(scipen = 999)
```


```{r}
input <- ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"

input <- "input/07"

pmat <- tibble(x = read_lines(input)) |> 
  grid_matrix(var = x)
# structure with a list of list, first level = row, second each beam coordinates (row, col)
beamer <- vector(mode = "list", length = nrow(pmat))
pos <- 1
                   # row, col
beamer[[pos]] <- list(c(pos, which(pmat[1,] == "S")))
nb_split <- 0




beamer_split <- function(pos) {
  # check if blocker are present for every beamer on this row
  for (beam in beamer[[pos - 1]]) {
    if (pmat[pos, beam[2]] == '^') {
      beamer[[pos]] <<- append(beamer[[pos]], list(c(pos, beam[2] - 1), c(pos, beam[2] + 1)))
      lgt <- length(beamer[[pos]])
      # remove duplicates
      beamer[[pos]] <<- unique(beamer[[pos]])
      nb_split <<- nb_split + 1
      
    } else { # we just go down but each beam from above
      beamer[[pos]] <<- append(beamer[[pos]], list(c(pos, beam[2])))
    }
  }
}
tic()
while (pos < nrow(pmat) - 1) {
  pos <- pos + 1
  beamer_split(pos)
 # message(paste("row ", pos))
}
toc()
nb_split
```

1562 1.138 sec

## Part 2

```{r}
# for animation

grid2tib <- function(m, pos) {
   m |> 
    as_tibble(.name_repair = \(x) paste0("c", seq_len(ncol(m)))) |> 
    mutate(run = pos,
           x = row_number(), .before = c1) |> 
    pivot_longer(cols = starts_with("c"),
                 names_to = "y",
                 names_prefix = "c",
                 names_transform = list(y = as.numeric),
                 values_to = "paths")
}


# count number of paths for part 2
beam_paths <- matrix(data = 0, nrow = nrow(pmat), ncol = ncol(pmat))
beam_paths[1, which(pmat[1,] == "S")] <- 1L

tpath <- vector(mode = "list", length = nrow(pmat))
tpath[[1]] <- grid2tib(beam_paths, 1)

tic()
for (i in 2:nrow(pmat)) {
  for (j in seq_len(ncol(pmat))) {
    b <- beam_paths[i - 1, j]
    if (pmat[i, j] == '^') {
      beam_paths[i, j - 1] <-  b + beam_paths[i, j - 1]
      beam_paths[i, j + 1] <-  b + beam_paths[i, j + 1]
    } else {
      beam_paths[i, j] <-  b + beam_paths[i, j]
    }
  tpath[[i]] <- grid2tib(beam_paths, i)
  }
}
sum(beam_paths[nrow(beam_paths),])
toc()
```

24292631346665 0.044 secs

```{r}
library(gganimate)

bind_rows(tpath) |> 
  filter(run == max(run)) |> 
  ggplot(aes(y, x, fill = log(paths))) +
  geom_tile() +
  #transition_reveal(run) +
  scale_fill_viridis_c(option = "turbo", na.value = "white") +
  scale_y_reverse() +
  theme_void() -> p
#animate(p)
ggsave("d07.png", plot = p, width = 11, height = 8.5, dpi = 250)
```

