---
format: html
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
```

## Part 1

```{r}
#| label: readin-input
read_lines(
"seeds: 79 14 55 13

seed-to-soil map:
50 98 2
52 50 48

soil-to-fertilizer map:
0 15 37
37 52 2
39 0 15

fertilizer-to-water map:
49 53 8
0 11 42
42 0 7
57 7 4

water-to-light map:
88 18 7
18 25 70

light-to-temperature map:
45 77 23
81 45 19
68 64 13

temperature-to-humidity map:
0 69 1
1 0 69

humidity-to-location map:
60 56 37
56 93 4") -> input
input <- read_lines("input/05")
```

```{r}
#| label: helpers
parse_map <- function(.data, type) {
  paste0(.data, collapse = "\n") |> 
    str_extract(pattern = paste0(type, " map:\n([\\d\\s]*)"), group = 1) |> 
    str_split_1("\n") |> 
    str_subset("\\d+") |> 
    map(\(x) {
      str_split_1(x, " ") |> 
        as.numeric()
      # 1 is destination, 2 is origin and 3 is the length
    })
}

find_correspondences <- function(query, intervals) {
  for (rg in intervals) {
    if (query >= rg[2] & query <= (rg[2] + rg[3] - 1L)) {
      return(query + rg[1] - rg[2])
    }
  }
  query
}
```

```{r}
#| label: part1
seeds <- str_subset(input, "^seeds") |> 
  str_extract(pattern = "seeds: ([\\d\\s]*)", group = 1) |> 
  str_split_1(" ") |> as.numeric()

fertilizer_types <- str_subset(input, "map") |> 
  str_extract("\\w+\\-to\\-\\w+")

fertilizer_types |> 
  set_names() |> 
  map(\(x) parse_map(input, x)) -> garden_map

seeds |> 
  map_dbl(\(x) find_correspondences(x, garden_map$`seed-to-soil`), .progress = "soil") |> 
  map_dbl(\(x) find_correspondences(x, garden_map$`soil-to-fertilizer`), .progress = "fertilizer") |> 
  map_dbl(\(x) find_correspondences(x, garden_map$`fertilizer-to-water`), .progress = "water") |> 
  map_dbl(\(x) find_correspondences(x, garden_map$`water-to-light`), .progress = "light") |> 
  map_dbl(\(x) find_correspondences(x, garden_map$`light-to-temperature`), .progress = "temperature") |> 
  map_dbl(\(x) find_correspondences(x, garden_map$`temperature-to-humidity`), .progress = "humidity") |> 
  map_dbl(\(x) find_correspondences(x, garden_map$`humidity-to-location`), .progress = "location") -> locations

min(locations)
```

## Part 2

```{r}
tibble(lg = seeds[seq(2, 20, 2)]) |> 
  summarise(sum(lg))
```

2,104,769,314 numbers to treat


```{r}
#| label: part2
library(GenomicRanges)

garden_map |> 
  map(\(x)  {
    map(x, \(rg) {
      GRanges(seqnames = "aoc",
              IRanges(start = rg[2], width = rg[3], shift = rg[1] - rg[2]))
    }) |> as("GRangesList") |> 
      do.call(c, args = _)
  }) -> garden_gr



seed_ir <- GRanges(seqnames = "aoc",
                   IRanges(start = c(79, 55), width = c(14, 13)))
                   #IRanges(start = c(82), end = 82)) |> 
                   #IRanges(start = c(79, 14, 55, 13), end = c(79, 14, 55, 13)))


find_shift_gr <- function(query, subject) {
  # return parts that are not in the soil intervals
  no_shift <- setdiff(query, subject)
  # part that needs shifting
  to_shift <- setdiff(query, no_shift)
  if (length(to_shift) == 0L) return(no_shift)
  # which interval for shifting
  ov <- findOverlaps(query, subject)
  map(seq_along(ov), \(x) {
    #message("query ", queryHits(ov)[x], " goes on soil ", subjectHits(ov)[x], " shift with ", soil$shift[subjectHits(ov)[x]])
    shift(to_shift[queryHits(ov)[x]], subject$shift[subjectHits(ov)[x]])
  })  -> shifted
  if (length(no_shift) == 0L) {
    return(shifted[[1]])
  }
  # add interval that didn't need shifting
  append(shifted, no_shift) |> 
    # must convert to Listobject before concatenation 
    # https://support.bioconductor.org/p/113168/#113169
    as("GRangesList") |> 
    do.call(c, args = _) #|> reduce()
}


find_shift_gr(seed_ir[1], garden_gr$`seed-to-soil`) |> 
  find_shift_gr(garden_gr$`soil-to-fertilizer`) |> 
  find_shift_gr(garden_gr$`fertilizer-to-water`) |> 
  find_shift_gr(garden_gr$`water-to-light`) |> 
  find_shift_gr(garden_gr$`light-to-temperature`) |> 
  find_shift_gr(garden_gr$`temperature-to-humidity`) |> 
  find_shift_gr(garden_gr$`humidity-to-location`)
  
```

86-89


takes too long, to be done in a more efficient language

soil: 7 intervals: 45 min
fertilizer: 46 intervals: 3h
water: 49 intervals: 2h
light: 23 intervals: 1h
temperature: 46 intervals: 2h
humidity: 16 intervals: 1h
location: 24 intervals: 


 312415190				
 106131293				
  30365957				
1183890307				
  13162298				
  74991378				
   3190497				
 226221606				
  87808390				
  66592398

