---
title: '03'
author: "A. Ginolhac"
date: "2021-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data


```{r}
d03_test <- tribble(
  ~ rates,
   "00100",
   "11110",
   "10110",
   "10111",
   "10101",
   "01111",
   "00111",
   "11100",
   "10000",
   "11001",
   "00010",
   "01010"
  )


d03 <- read_table("input/03", col_names = "rates")

```


## Part 1


gamma:

```{r}
lg <- str_length(d03$rates[1])

d03 |> 
  separate(rates, letters[1:lg], sep = 1:lg, 
           convert = TRUE) |> 
  map_dbl(sum) |> 
  map_int(~ .x > nrow(d03) / 2) |> 
  paste0(collapse = "") |> 
  base::strtoi(base = 2) -> gamma
gamma
```

epsilon:

```{r}
d03 |> 
  separate(rates, letters[1:lg], sep = 1:lg,
           convert = TRUE) |> 
  map_dbl(sum) |> 
  map_int(~ .x < nrow(d03) / 2) |> 
  paste0(collapse = "") |> 
  base::strtoi(base = 2) -> epsilon
epsilon
```

answer: `r epsilon * gamma`

### Part 2

```{r}
lg <- str_length(d03_test$rates[1])

most_common <- function(vec, type = c("CO2", "O2")) {
  type = match.arg(type)
  if (length(vec) == 2L) {
    if (type == "CO2") {
      return(0L)
    } else return(1L) # O2
  }
  mc <- as.integer(sum(vec) > length(vec) / 2L)
  message(mc, length(vec))
  mc
}

# interesting but not serial
d03_test |> 
  separate(rates, letters[1:lg], sep = 1:lg,
           convert = TRUE) |> 
  filter(if_all(everything(), ~ .x == most_common(.x, "O2"))) |> 
  glue::glue_collapse() |> 
  strtoi(base = 2L)
```


- Oxygen

```{r}
lg <- str_length(d03_test$rates[1])
d03_test |> 
  separate(rates, letters[1:lg], sep = 1:lg,
           convert = TRUE) -> tt
type <- "O2"
for (i in seq_len(lg)) {
  print(tt)
  input <- tt[[i]]
  if (length(input) == 2L) {
    if (type == "CO2") {
      tt <<- tt[input == 0L, ]
    } else {
      tt <<- tt[input == 1L, ] # O2
    }
    break
  }
  mc <- as.integer(sum(input) > length(input) / 2L)
  tt <<- tt[input == mc, ]
}
tt |> 
  glue::glue_collapse() |> 
  strtoi(base = 2L)
```


- CO2

```{r}
lg <- str_length(d03_test$rates[1])
d03_test |> 
  separate(rates, letters[1:lg], sep = 1:lg,
           convert = TRUE) -> tt
type <- "CO2"
for (i in seq_len(lg)) {
  print(tt)
  input <- tt[[i]]
  if (length(input) == 2L) {
    if (type == "CO2") {
      tt <<- tt[input == 0L, ]
    } else {
      tt <<- tt[input == 1L, ] # O2
    }
    break
  }
  mc <- as.integer(sum(input) < length(input) / 2L)
  tt <<- tt[input == mc, ]
}
tt |> 
  glue::glue_collapse() |> 
  strtoi(base = 2L)
```


```{r}
787 * 3586
```

