---
title: '06'
author: "A. Ginolhac"
date: "2021-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data


```{r}
test <- list(c(3L, 4L, 3L, 1L, 2L))
input <- read_lines("input/06") |> 
  str_split(",") |>
  pluck(1) |> 
  as.integer() |> 
    list()
```


## Part 1


```{r}
input <- test

simul <- function(vec) {
  out <- vector(mode = "integer", length = length(vec))
  new <- 0L
  for (i in seq_along(vec)) {
    if (vec[i] == 0L) {
      out[i] <- 6L
      new <- new + 1L
    } else {
      out[i] <- vec[i] - 1L
    }
  }
  # add the new fishes
  for (x in seq_len(new)) {
   out[length(vec) + x] <- 8L
  }
  out
}
# test
map(input, simul) |> 
  map(simul) 

# simulation
for (days in seq_len(256L)) {
  input <<- map(input, simul)
  #message("days ", days, input)
}
print(length(input[[1]]))
```


### Part 2

Above approach is too greedy for more than 80 days.

Fishes need to be counted at each step per age category, not individually

```{r}
age_count <- vector(mode = "integer", length = 9L) # R not 0 based

for (day in seq_len(3L)) {
  # intialisation
  if (day == 1L)
  for (x in test) {
    age_count[x + 1] <- age_count[x + 1] + 1
  }
}
print(age_count)
```

