---
format: html
---


```{r}
#| label: setup
#| include: false

library(tidyverse)
```


## Part 1



```{r}
input <- read_lines(I(
  "London to Dublin = 464
London to Belfast = 518
Dublin to Belfast = 141"
))

input <- read_lines("input/09")

cities <- str_extract_all(input, "\\w+") |>
  map(\(x) discard(x, x == "to" | str_detect(x, "\\d+"))) |>
  flatten_chr() |>
  unique()
# create matrix with names
mdistance <- matrix(
  numeric(length(cities)**2),
  nrow = length(cities),
  ncol = length(cities)
)
rownames(mdistance) <- cities
colnames(mdistance) <- cities

parse_distances <- function(line, mat) {
  loc <- str_split_i(line, " = ", 1) |> str_split_1(" to ")
  distance <- str_extract(line, "\\d+$") |> as.integer()
  mat[loc[1], loc[2]] <- distance
  mat[loc[2], loc[1]] <- distance
  mat
}
# fill in the matrix of distance
for (line in input) {
  mdistance <- parse_distances(line, mdistance)
}
mdistance
```



```{r}
colSums(mdistance) |> min()
```


333 too high

Need all permutations

```{r}
gtools::permutations(
  n = length(cities),
  r = length(cities),
  v = cities,
  repeats.allowed = FALSE
) -> possible_paths

compute_distance <- function(line) {
  dist <- 0
  for (i in seq_len(length(line) - 1L)) {
    dist <- dist + mdistance[line[i], line[i + 1L]]
  }
  dist
}

possible_distance <- vector(mode = "integer", length = nrow(possible_paths))
for (i in seq_len(nrow(possible_paths))) {
  possible_distance[i] <- compute_distance(possible_paths[i, ])
}
min(possible_distance)
```


141 603ms

## Part 2


```{r}
max(possible_distance)
```