---
format: html
---


```{r}
#| label: setup
#| include: false

library(tidyverse)
```


## Part 1



```{r}

input <- read_lines(I(
  "Comet can fly 14 km/s for 10 seconds, but then must rest for 127 seconds.
Dancer can fly 16 km/s for 11 seconds, but then must rest for 162 seconds."
))


input <- read_lines("input/14")

reindeer <- vector(mode = "list", length = length(input))
names(reindeer) <- str_extract_all(input, "^\\w+") |> unlist()
# parse input
for (i in seq_along(input)) {
  reindeer[[i]]$rest <- str_extract(
    input[i],
    "(\\d+) seconds\\.$",
    group = 1L
  ) |>
    as.integer()
  reindeer[[i]]$duration <- str_extract(
    input[i],
    "(\\d+) seconds",
    group = 1L
  ) |>
    as.integer()
  reindeer[[i]]$speed <- str_extract(input[i], "(\\d+) km/s", group = 1L) |>
    as.integer()
}
```

Travel

```{r}
time_goal <- 2503

for (r in seq_along(reindeer)) {
  flight_unit <- c(
    rep(reindeer[[r]]$speed, reindeer[[r]]$duration),
    rep(0, reindeer[[r]]$rest)
  )
  nb_cycles <- time_goal / length(flight_unit)
  flight <- rep(flight_unit, ceiling(nb_cycles))
  message(paste(r, names(reindeer)[r], sum(flight[seq_len(time_goal)])))
}
```


Rudolph 2640


## Part 2

Important thing I missed:

> (If there are multiple reindeer tied for the lead, they each get one point.)

```{r}
time_goal <- 2503

for (r in seq_along(reindeer)) {
  flight_unit <- c(
    rep(reindeer[[r]]$speed, reindeer[[r]]$duration),
    rep(0, reindeer[[r]]$rest)
  )
  nb_cycles <- time_goal / length(flight_unit)
  flight <- rep(flight_unit, ceiling(nb_cycles))
  # add info for flight
  reindeer[[r]]$travel <- flight[seq_len(time_goal)]
  reindeer[[r]]$travel_cs <- cumsum(flight[seq_len(time_goal)])
  message(paste(r, names(reindeer)[r], sum(flight[seq_len(time_goal)])))
}

map(reindeer, pluck, "travel_cs") |>
  transpose() |>
  enframe(value = "travel_cs") |>
  mutate(travel_cs = map(travel_cs, unlist)) |>
  mutate(
    win_idx = map(travel_cs, \(x) {
      is_ties <- sum(max(x) == x) > 1L
      if (is_ties) {
        # ties leader get a point
        set_names(which(x == max(x)), names(reindeer)[which(x == max(x))])
      } else {
        which.max(x)
      }
    })
  ) -> travels

unnest_longer(travels, win_idx) |>
  count(win_idx_id, sort = TRUE)
```

1063 too low
1229 too high (1102)






```{r}
#| fig-width: 7
#| fig-height: 6
unnest_longer(travels, travel_cs) |>
  ggplot(aes(x = name, y = travel_cs, colour = travel_cs_id)) +
  geom_line() +
  theme_bw(14) +
  labs(x = "seconds", y = "distance (km)", colour = "Reindeer")
```



```{r}
library(gganimate)


travels |>
  #slice_head(n = 1000) |>
  slice_sample(prop = 0.25) |> 
  unnest_longer(travel_cs) |>
  mutate(
    winner = map_chr(win_idx, \(i) names(reindeer)[i] |> paste(collapse = ' '))
  ) |>
  ggplot(aes(x = name, y = travel_cs, colour = travel_cs_id)) +
  geom_line(aes(group = travel_cs_id)) +
  geom_label(
    data = \(x) filter(x, travel_cs_id == winner),
    aes(label = winner, colour = travel_cs_id),
    nudge_y = 10,
    nudge_x = -5,
    show.legend = FALSE
  ) +
  transition_reveal(along = name) +
  theme_bw(14) +
  coord_cartesian(clip = 'off') +
  labs(x = "seconds", y = "distance (km)", colour = "Reindeer") -> p
ap <- animate(p)
save_animation(ap, "reindeer.gif")
```