---
format: html
---


```{r}
#| label: setup
#| include: false

library(tidyverse)
```


## Part 1

```{r}
input <- read_lines(I(
  "Sprinkles: capacity 2, durability 0, flavor -2, texture 0, calories 3
Butterscotch: capacity 0, durability 5, flavor -3, texture 0, calories 3
Chocolate: capacity 0, durability 0, flavor 5, texture -1, calories 8
Candy: capacity 0, durability -1, flavor 0, texture 5, calories 8"
))


# input <- read_lines(I(
#   "Butterscotch: capacity -1, durability -2, flavor 6, texture 3, calories 8
# Cinnamon: capacity 2, durability 3, flavor -2, texture -1, calories 3"
# ))

recipe <- vector(mode = "list", length = 0L)

parse_ingredients <- function(line, r) {
  ing <- str_extract(line, "^\\w+")
  nbs <- str_extract_all(line, "-?\\d+")[[1]] |> as.integer()
  r[[ing]] <- nbs
  r
}

for (l in input) {
  recipe <- parse_ingredients(l, recipe)
}
recipe
```

Generate combinations and permutations of them

```{r}
max_p <- 100 #- (length(input) - 1L)
mat_prop <- gtools::combinations(
  v = seq(0, max_p),
  r = length(input),
  n = max_p,
  repeats.allowed = TRUE
)
mat_prop <- mat_prop[rowSums(mat_prop) == 100, ]

perms <- gtools::permutations(length(input), r = length(input))
t(perms) |>
  as.data.frame() |>
  map(\(x) mat_prop[, x] |> as.data.frame()) |>
  list_rbind() |>
  as.matrix() |>
  t() -> comp_ag

# all above can be done in one go with that:
#comp <- partitions::compositions(100, 4) |> as.matrix()

# now test it all and store in scores
scores <- vector(mode = "double", length = ncol(comp))

for (c in seq_len(ncol(comp_ag))) {
  sum_recipe <- (comp_ag[1, c] * recipe[[1]]) +
    (comp_ag[2, c] * recipe[[2]]) +
    (comp_ag[3, c] * recipe[[3]]) +
    (comp_ag[4, c] * recipe[[4]])
  # remove calories for now
  sum_recipe <- sum_recipe[-5]
  if (any(sum_recipe < 0)) {
    sum_recipe <- 0
  }
  scores[c] <- prod(sum_recipe)
}
max(scores)
comp_ag[, which.max(scores)]
```

18734912 too low
19150560 too low
correct: 21367368 2 sec

recipe propotions:
V1 V2 V3 V4 
17 19 38 26 

## Part 2

Using https://cran.r-project.org/web/packages/partitions/refman/partitions.html#parts

```{r}
comp <- partitions::compositions(100, length(input)) |> as.matrix()

# now test it all and store in scores
scores2 <- vector(mode = "double", length = ncol(comp))

for (c in seq_len(ncol(comp))) {
  sum_recipe <- (comp[1, c] * recipe[[1]]) +
    (comp[2, c] * recipe[[2]]) +
    (comp[3, c] * recipe[[3]]) +
    (comp[4, c] * recipe[[4]])
  calories <- sum_recipe[5]
  sum_recipe <- sum_recipe[-5]
  if (any(sum_recipe < 0) || calories != 500) {
    sum_recipe <- 0
  }
  # message(paste(
  #   mat_prop[i, perms[p, 1]],
  #   mat_prop[i, perms[p, 2]],
  #   mat_prop[i, perms[p, 3]],
  #   mat_prop[i, perms[p, 4]]
  #   prod(sum_recipe),
  #   collapse = ' '
  # ))
  scores2[c] <- prod(sum_recipe)
}
max(scores2)
comp[, which.max(scores2)]
```

1766400 193ms

composition:
[1] 46 14 30 10