---
format: html
---


```{r}
#| label: setup
#| include: false

library(tidyverse)
library(adventdrob)
library(gganimate)
```


## Part 1




```{r}
input <- read_lines(I(
  ".#.#.#
...##.
#....#
..#...
#.#..#
####.."
))

input <- read_lines("input/18")

tibble(x = str_replace_all(input, c('#' = '1', '\\.' = '0'))) |>
  grid_tidy(var = x) -> light_grid
light_grid
```




```{r}
update_light <- function(d) {
  d |>
    adjacent_join(diagonal = TRUE) |>
    summarise(on_neighbor = sum(value2), .by = c(row, value, col)) |>
    mutate(
      new_value = case_when(
        value == 1 & (on_neighbor == 2 | on_neighbor == 3) ~ 1,
        value == 1 ~ 0,
        value == 0 & on_neighbor == 3 ~ 1,
        value == 0 ~ 0,
        .unmatched = "error"
      )
    ) |>
    select(-on_neighbor) |>
    right_join(d, by = join_by(row, value, col)) |>
    mutate(value = new_value) |>
    select(-new_value)
}


cycles <- 0

res <- vector(mode = "list", length = 2000L)

while (cycles <= 2000) {
  if (cycles %% 100 == 0) {
    message(paste(
      "cycle",
      cycles,
      summarise(light_grid, s = sum(value)) |>
        pull(s)
    ))
  }
  res[[cycles + 1]] <- light_grid
  light_grid <- update_light(light_grid)
  cycles <- cycles + 1
}
```


2569 too high
2330 too high. Stupid me stuck at 4 cycles
768 4.5 sec


```{r}
#| eval: false

list_rbind(res[1:10], names_to = "cycle") |>
  ggplot(aes(y = -row, x = col, fill = factor(value))) +
  geom_tile() +
  facet_wrap(~cycle, labeller = label_both) +
  scale_fill_manual(values = c("0" = "grey95", "1" = "purple")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), labels = \(x) abs(x)) +
  transition_states(cycle, transition_length = 0.2, state_length = 0.5) +
  theme_classic() +
  theme(panel.grid.major = element_line(colour = "grey")) +
  coord_equal() +
  labs(fill = "light", y = "row", title = "cycle: {closest_state}") -> p
anilight <- animate(p)
anim_save("anilight.gif")
#ggsave("d18.pdf", width = 8, height = 8)
```


## Part 2

Corners always on

```{r}
turn_on_corners <- function(d) {
  d |>
    mutate(
      value = replace_when(
        value,
        row == 1 & col == 1 ~ 1,
        row == 1 & col == max(col) ~ 1,
        row == max(row) & col == 1 ~ 1,
        row == max(row) & col == max(col) ~ 1,
      )
    )
}

cycles <- 0

res2 <- vector(mode = "list", length = 100L)

while (cycles <= 100) {
  light_grid <- turn_on_corners(light_grid)
  if (cycles %% 10 == 0) {
    message(paste(
      "cycle",
      cycles,
      summarise(light_grid, s = sum(value)) |>
        pull(s)
    ))
  }
  res2[[cycles + 1]] <- light_grid
  light_grid <- update_light(light_grid)
  cycles <- cycles + 1
}
```

781 6.2 sec


```{r}
list_rbind(res2, names_to = "cycle") |>
  ggplot(aes(y = -row, x = col, fill = factor(value))) +
  geom_tile() +
  facet_wrap(~cycle, labeller = label_both) +
  scale_fill_manual(values = c("0" = "grey95", "1" = "purple")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), labels = \(x) abs(x)) +
  theme_classic() +
  theme(panel.grid.major = element_line(colour = "grey")) +
  coord_equal() +
  labs(fill = "light", y = "row")
```


Playing with more cycles

```{r}
tibble(x = str_replace_all(input, c('#' = '1', '\\.' = '0'))) |>
  grid_tidy(var = x) -> light_grid

cycles <- 0

res2 <- vector(mode = "list", length = 2000L)

while (cycles <= 2000) {
  light_grid <- turn_on_corners(light_grid)
  if (cycles %% 200 == 0) {
    message(paste(
      "cycle",
      cycles,
      summarise(light_grid, s = sum(value)) |>
        pull(s)
    ))
  }
  res2[[cycles + 1]] <- light_grid
  light_grid <- update_light(light_grid)
  cycles <- cycles + 1
}
```

Animate both part for number of lights

```{r}
bind_rows(
  "part1" = list_rbind(res, names_to = "cycle"),
  "part2" = list_rbind(res2, names_to = "cycle"),
  .id = "part"
) |>
  filter(cycle < 1200) |>
  summarise(s = sum(value), .by = c(part, cycle)) |>
  ggplot(aes(x = cycle, y = s, colour = part)) +
  geom_line(aes(group = part)) +
  transition_reveal(along = cycle) +
  theme_bw(14) +
  theme(legend.position = "inside", legend.position.inside = c(0.6, 0.7)) +
  scale_y_log10(guide = "axis_logticks") +
  labs(y = "# lights on", colour = NULL) -> p2
anilight2 <- animate(p2)
anim_save("anilight2.gif")
```



```{r}
bind_rows(
  "1" = list_rbind(res, names_to = "cycle"),
  "2" = list_rbind(res2, names_to = "cycle"),
  .id = "part"
) |>
  filter(cycle < 36) |>
  mutate(id = paste0(row, '_', col)) |>
  ggplot(aes(y = -row, x = col, fill = factor(value))) +
  geom_tile(aes(group = id)) +
  transition_time(time = cycle) +
  facet_wrap(~part, labeller = label_both) +
  scale_fill_manual(values = c("0" = "grey95", "1" = "purple")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0), labels = \(x) abs(x)) +
  theme_classic(14) +
  theme(legend.position = "top") +
  coord_equal() +
  labs(fill = "light", y = "row", title = "cycle: {frame_time}") -> p3
anilight3 <- animate(p3, width = 820, height = 560)
anim_save("anilight3.gif")
```