---
format: html
---


```{r}
#| label: setup
#| include: false
library(tidyverse)
```

## Part 1


```{r}
boss <- list(hits = 55, Damage = 8)

player <- list(hits = 55, mana = 500, Armor = 0)

spells <- tribble(
  ~Name           , ~Cost , ~Damage , ~Armor , ~Duration ,
  "Magic Missile" ,   -53 ,       4 ,      0 , NA        ,
  "Drain"         ,   -73 ,       2 ,      0 , NA        , # +2 hits
  "Shield"        ,  -113 ,       0 ,      7 ,         6 ,
  "Poison"        ,  -173 ,       3 ,      0 ,         6 ,
  "Recharge"      ,  -229 ,       0 ,      0 ,         5 # +101 mana
) |>
  mutate(ID = row_number(), .before = 1)
spells
```


- Combinations

On each of your turns, you must select one of your spells to cast. 
If you cannot afford to cast any spell, you lose. 

```{r}
mingled_recharge <- function(v, r) {
  duration <-  ifelse (r + 5 > length(v), length(v), r + 5)
  message(paste(r, duration))
  for (i in seq(r, duration, 2L)) {
    v <- append(v, 101, after = i)
      print(v)
  }

}
mingled_recharge(c(1:10), r = 3)


check_duration <- function(v) {
  # check shield and poison don't overlap
  s <- any(diff(which(v == 3)) < 6)
  p <- any(diff(which(v == 4)) < 6)
  # check Recharge
  r <- any(diff(which(v == 5)) < 5)
  !any(s, p, r)
}
check_duration(c(3, 1, 2, 1, 2, 3))
check_duration(c(5, 1, 2, 1, 5, 1))

mana_cost <- function(v, mana = 500) {
  tibble(ID = v) |>
    left_join(spells, by = join_by(ID)) |>
    pull(Cost) |>
    unlist() -> mana_spent
  # Recharge
  recharge <- which(v == 5)
  for (r in recharge) {
    mana_spent <- mingled_recharge(mana_spent, r)
  }
  message(v)
  message(mana_spent)
  cost <- c(mana, mana_spent) |>
    cumsum()
  any(cost < 0)
}


mana_cost(c(2, 1, 3, 5, 4))
# FIXME delete casting a spell still active
gtools::combinations(5, r = 10, repeats.allowed = TRUE) |>
  t() |>
  as.data.frame() |>
  keep(check_duration) |>
  keep(mana_cost)
```