---
format: html
---


```{r}
#| label: setup
#| include: false

library(fastmap)
library(stringr)
```




```{r}
input <- readr::read_lines(I(
  "inc a
jio a, +2
tpl a
inc a"
))

input <- readr::read_lines("input/23")

input
```



```{r}
parse_instructions <- function(line) {
  #message(line)
  instruc <- str_extract(line, "^\\w+")
  if (instruc == "hlf") {
    # half on integer, floor?
    r <- str_extract(line, "[ab]$")
    regis$set(r, floor(regis$get(r) / 2))
  } else if (instruc == "tpl") {
    r <- str_extract(line, "[ab]$")
    regis$set(r, regis$get(r) * 3)
  } else if (instruc == "inc") {
    r <- str_extract(line, "[ab]$")
    regis$set(r, regis$get(r) + 1)
  } else if (instruc == "jmp") {
    r <- str_extract(line, "[ab]$")

    val <- str_extract(line, ".\\d+$")
    return(as.integer(val))
  } else if (instruc == "jie") {
    r <- str_extract(line, "([ab]),", group = 1)
    # only if even
    if (regis$get(r) %% 2 == 0) {
      val <- str_extract(line, ".\\d+$")
      return(as.integer(val))
    }
  } else if (instruc == "jio") {
    r <- str_extract(line, "([ab]),", group = 1)
    # only if 1
    if (regis$get(r) == 1) {
      val <- str_extract(line, ".\\d+$")
      return(as.integer(val))
    }
  } else {
    srop("wrong instruction")
  }
  NULL
}


regis <- fastmap()
regis$set('a', 0)
regis$set('b', 0)

i <- 1
while (i <= length(input)) {
  v <- parse_instructions(input[i])
  if (!is.null(v)) {
    i <- i + v
  } else {
    i <- i + 1
  }
}


regis$get('a')
regis$get('b')
```


255 1sec


## Part 2



```{r}
regis <- fastmap()
regis$set('a', 1)
regis$set('b', 0)

i <- 1
while (i <= length(input)) {
  v <- parse_instructions(input[i])
  if (!is.null(v)) {
    i <- i + v
  } else {
    i <- i + 1
  }
}


regis$get('a')
regis$get('b')
```