
```{r}
#| label: setup
#| include: false

library(tidyverse)
library(fastmap)
```


## Part 1

using a hashtable https://r-lib.github.io/fastmap/

```{r}
coord2str <- function(coord) paste(coord, collapse = '|')
str2coord <- function(str) str_split_1(str, fixed('|')) |> as.numeric()

head_travel <- function(h, instruc, prev) {
  move <- str_extract(instruc, "^[A-Z]")
  val <- str_extract(instruc, "\\d+$") |> as.integer()
  if (move == 'U') {
    for (i in min(prev[2], val):max(prev[2], val)) {
      new <- coord2str(c(i, prev[2]))
      h$set(new, h$get(new) + 1)
    }
  } else if (move == 'L') {
    for (i in min(prev[1], val):max(prev[1], val)) {
      new <- coord2str(c(prev[1], i))
      h$set(new, h$get(new) + 1)
    }
  } else if (move == 'R') {
    for (i in min(prev[1], val):max(prev[1], val)) {
      new <- coord2str(c(prev[1], i))
      h$set(new, h$get(new) + 1)
      message(paste("R new ", new, "h ", h$get(new)))
    }
  } else if (move == 'D') {
    for (i in min(prev[2], val):max(prev[2], val)) {
      new <- coord2str(c(i, prev[2]))
      h$set(new, h$get(new) + 1)
    }
  } else {
    stop("Unknown input")
  }

  message(paste("move ", move, "new ", new, "h ", h$get(new)))
  str2coord(new)
}
```

```{r}
head <- fastmap(missing_default = 0L)

input <- read_lines(I(
  "R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2"
))


#input <- read_lines("input/09")

start <- c(0, 0)

head$set(coord2str(start), 1)

for (m in input) {
  start <- head_travel(head, m, start)
}
```


```{r}
#| eval: false
for (k in head$keys()) {
  message("key: ", k, ": ", head$get(k))
}
```

