---
title: '02'
author: "A. Ginolhac"
date: "2021-12-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

##


```{r}
d02 <- read_table("input/02", col_names = c("direction", "value"))


# d02 <- tribble(
#   ~ direction, ~ value,
#   "forward", 5,
#   "down", 5,
#   "forward", 8,
#   "up", 3,
#   "down", 8,
#   "forward", 2,
# )
```


### Part 1

```{r}
d02 |>
  group_by(direction) |> 
  summarise(sum = sum(value)) |> 
  pivot_wider(names_from = direction,
              values_from = sum) |> 
  mutate(depth = down - up,
         solution = depth * forward)
```

- Answer is 2322630

### Part 2

```{r}
aim <- 0
depth <- 0
fw <- 0
message("aim\tfw\tdepth")
for (i in seq_along(d02$direction)) {
#for (i in 1:20) {
  val <- d02$value[i]
  if (d02$direction[i] == "forward") {
    depth <- depth + (val * aim)
    fw <- fw + val
  } else if (d02$direction[i] == "down") {
    aim <- aim + val
  }
  else {
    aim <- aim - val
  }
  
  #message(paste(d02$direction[i], val, aim, fw, depth, sep = "\t"))
}
message(paste(aim, fw, depth, sep = "\t"))
1965*1071386
```

- answer is 2105273490
