---
title: '03'
author: "A. Ginolhac"
date: "2021-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data


```{r}
d03_test <- tribble(
  ~rates  ,
  "00100" ,
  "11110" ,
  "10110" ,
  "10111" ,
  "10101" ,
  "01111" ,
  "00111" ,
  "11100" ,
  "10000" ,
  "11001" ,
  "00010" ,
  "01010"
)


d03 <- read_table("input/03", col_names = "rates", show_col_types = FALSE)
d03
```


## Part 1


gamma:

```{r}
lg <- str_length(d03$rates[1])

d03 |>
  separate(rates, letters[1:lg], sep = 1:lg, convert = TRUE) |>
  map_dbl(sum) |>
  map_int(~ .x > nrow(d03) / 2) |>
  paste0(collapse = "") |>
  base::strtoi(base = 2) -> gamma
gamma
```

epsilon:

```{r}
d03 |>
  separate(rates, letters[1:lg], sep = 1:lg, convert = TRUE) |>
  map_dbl(sum) |>
  map_int(~ .x < nrow(d03) / 2) |>
  paste0(collapse = "") |>
  base::strtoi(base = 2) -> epsilon
epsilon
```

answer: `r epsilon * gamma`

### Part 2


```{r}
lg <- str_length(d03$rates[1])


bit_criteria <- function(vec, type = c("CO2", "O2")) {
  type <- match.arg(type)
  if (sum(vec) == (length(vec) / 2L)) {
    if (type == "CO2") {
      return(0L)
    } else {
      # O2
      return(1L)
    }
  } else if (sum(vec) > (length(vec) / 2L) && type == "O2") {
    return(1L)
  } else if (sum(vec) > (length(vec) / 2L) && type == "CO2") {
    return(0L)
  } else if (sum(vec) < (length(vec) / 2L) && type == "O2") {
    return(1L)
  } else if (sum(vec) < (length(vec) / 2L) && type == "CO2") {
    return(0L)
  } else {
    stop("should not happen!")
  }
}


# using recursion
life_support_rating <- function(dat, idx = 1L, type = c("CO2", "O2")) {
  type <- match.arg(type)
  cat("idx =", idx, " nrow =", nrow(dat), "\n")
  if (nrow(dat) == 1L) {
    return(dat)
  }
  if (idx > ncol(dat)) {
    warning("Ran out of columns with ", nrow(dat), " rows remaining")
    return(dat)
  }
  keep <- dat[[idx]] == bit_criteria(dat[[idx]], type = type)
  # edge case for CO2 we could not filter anything
  if (!any(keep)) {
    filtered <- dat
  } else {
    filtered <- dat[keep, , drop = FALSE]
  }
  life_support_rating(filtered, idx + 1L, type = type)
}

#life_support_rating(dat, type = "O2")
#life_support_rating(dat, type = "CO2")

d03 |>
  separate(
    rates,
    letters[seq_len(lg)],
    sep = seq_len(lg),
    convert = TRUE
  ) |>
  # to be able to return a vector from column selection
  as.data.frame() -> dat

life_support_rating(dat, type = "O2") |>
  glue::glue_collapse() |>
  strtoi(base = 2L) *
  life_support_rating(dat, type = "CO2") |>
    glue::glue_collapse() |>
    strtoi(base = 2L)
```




20470 too low


intToBits(789) |> rev() |> as.integer() |> paste(collapse = '') 001100010101
intToBits(3589) |> rev() |> as.integer() |> paste(collapse = '')
# [1] "00000000000000000000000000001100"
