---
title: '06'
author: "A. Ginolhac"
date: "2021-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data


```{r}


test <- list(c(3L, 4L, 3L, 1L, 2L))
input <- read_lines("input/06") |> 
  str_split(",") |>
  pluck(1) |> 
  as.integer() |> 
    list()
```


## Part 1


```{r}
input <- test

simul <- function(vec) {
  out <- vector(mode = "integer", length = length(vec))
  new <- 0L
  for (i in seq_along(vec)) {
    if (vec[i] == 0L) {
      out[i] <- 6L
      new <- new + 1L
    } else {
      out[i] <- vec[i] - 1L
    }
  }
  # add the new fishes
  for (x in seq_len(new)) {
   out[length(vec) + x] <- 8L
  }
  out
}
# test
map(input, simul) |> 
  map(simul) 

# simulation
for (days in seq_len(256L)) {
  input <<- map(input, simul)
  #message("days ", days, input)
}
print(length(input[[1]]))
```


### Part 2

Above approach is too greedy for more than 80 days.

Fishes need to be counted at each step per age category, not individually

```{r}
age_count <- vector(mode = "integer", length = 9L) # R not 0 based

for (day in seq_len(8L)) {
  # intialisation
  if (day == 1L)
  for (x in test[[1]]) {
    age_count[x + 1] <- age_count[x + 1] + 1
  } else {
    new <- age_count[1]
    age_count <- lead(age_count)
    # fish arrives to zero so
    # 1. create a number 8
    age_count[9] <- new
    # 2. convert to a 6
    age_count[7] <- new
  }
  message("day", day, " fishes: ", age_count)
}
print(age_count)
```


Miles Mc Bain solution https://twitter.com/MilesMcBain/status/1468888082908782592?s=20

```{r}
options(scipen = 999)

fish_ages <- scan("input/06", what = integer(), sep = ",") |> 
  table() |> 
  as.list() |> 
  modifyList(x = setNames(as.list(rep(0, length(seq(-1, 8)))), seq(-1, 8)))


shift_list_left <- function(a_list) {
  list_names <- names(a_list)
  c(a_list[-1], 0) |> 
    setNames(list_names)
}

new_population <- reduce(.x = seq(256L),
                         .init = fish_ages,
                         .f = function(fish_ages, epoch) {
                           new_ages <- shift_list_left(fish_ages)
                           reproducing <- new_ages[["-1"]]
                           new_ages["-1"] <- 0
                           new_ages["8"] <- reproducing
                           new_ages["6"] <- new_ages[["6"]] + reproducing
                           new_ages
                         })
do.call(sum, new_population)
```

