---
title: '09'
author: "A. Ginolhac"
date: "2021-12-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Plot


```{r}
read_lines("input/09") |> 
  str_split(pattern = '') |>
  map(as.integer) |> 
  enframe(name = "Y") |>
  unnest_longer(value) |> 
  group_by(Y) |> 
  mutate(X = row_number()) |> 
  ggplot(aes(X, Y, fill = value)) +
  geom_raster() +
  scale_fill_viridis_c(option = "A", direction = -1L) +
  theme_void()
ggsave("d09.png", width = 5, height = 5)
```
### Adjacent using David Robinson

Diagonal is off

```{r}
library(adventdrob) # renv::install("dgrtwo/adventdrob")
x <- read_tsv("input/09", col_names = "x", show_col_types = FALSE) |> 
  grid_tidy(x) %>% 
  adjacent_join(diagonal = FALSE)
x
```
Part 1

```{r}
x %>% 
  group_by(row, col, value) %>% 
  summarise(low = all(value < value2), .groups = "drop") %>% 
  filter(low) %>%
  mutate(risks = value + 1) %>% 
  summarise(sum(risks))
```
- 545

### Part 2

Solution from David [here](https://twitter.com/drob/status/1469037082777726986)
