---
title: '10'
author: "A. Ginolhac"
date: "2021-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data


```{r}
input <- read_lines("input/10") %>% 
  str_split(pattern = '')
head(input, 3) %>% 
  str_split(pattern = '') -> inp
inp %>% 
  str_split(pattern = '') %>% 
  map(table)
```

- only closing / opening

```{r}
input %>% 
  map(str_replace_all, "[\\(\\[\\{\\<]", "O") %>% 
  map(str_replace_all, "[\\)\\]\\}\\>]", "C") %>% 
  map(str_count, c("O", "C"))
```

stack

```{r}
coresp <- c("(" = ")", "[" = "]", "{" = "}", "<" = ">")
scores <- c(")" = 3, "]" = 57, "}" = 1197, ">" = 25137)


parse_closing <- function(line) {
  stak <- c()
  for (ch in line) {
    #print(ch)
    if (ch %in% c("(", "[", "{", "<")) {
      stak <- c(ch, stak)
    } else {
      # closing characters
      expected <- coresp[stak[1L]]
      if (expected != ch) {
        #message("stop! ", "found ", ch, " expected ", expected)
        return(scores[ch])
      } else {
        stak <- stak[-1L]
      }
    }
  }
  return(0)
}

sum(map_dbl(input, parse_closing))
```


```{r}
# get incomplete lines
incomplete <- read_lines("input/10")[if_else(map_dbl(input, parse_closing) == 0, TRUE, FALSE)] %>% 
  str_split('')

second_scores <- c("(" = 1, "[" = 2, "{" = 3, "<" = 4)

correct_closing <- function(line) {
  stak <- c()
  for (ch in line) {
    #print(ch)
    if (ch %in% c("(", "[", "{", "<")) {
      stak <- c(ch, stak)
    } else {
      # closing characters
      expected <- coresp[stak[1L]]
      if (expected != ch) {

      } else {
        stak <- stak[-1L]
      }
    }
  }
  return(map_dbl(stak, ~ second_scores[.x]))
}

map(incomplete, correct_closing) %>% 
  map_dbl(~ reduce(.x, .init = 0, ~ .x * 5 + .y)) %>% 
  median()

```

