---
title: '11'
author: "A. Ginolhac"
date: "2021-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data


see D. Robinson adjacent function [here](https://twitter.com/drob/status/1469037082777726986?s=20)

Using his package [`adventdrob`](https://github.com/dgrtwo/adventdrob) and own [solution](https://twitter.com/drob/status/1469766453771522056?s=20)

```{r}
library(adventdrob) # renv::install("dgrtwo/adventdrob")
x <- read_tsv("input/11", col_names = "x", show_col_types = FALSE) |> 
  grid_tidy(x)
```
### Testing adjacent_nest

```{r}
adjacent_nest(x) 
```


### Testing adjacent_join

See [issue](https://github.com/dgrtwo/adventdrob/issues/1)

```{r}
adventdrob:::adjacent_join(x, diagonal = TRUE) 
```

### Main loop by David Rovinson


```{r}

part1 <- 0

x_anim <- tribble(
  ~row, ~col, ~value, ~flash, ~has_flashed, ~step
)

for (i in seq_len(100)) { # 100 for part1 1000 for Part 2
  x <- x |> 
    mutate(value = value + 1,
           flash = value > 9,
           has_flashed = flash)
  while (any(x$flash)) {
    # Keep counts for part1
    part1 <- part1 + sum(x$flash)
    x <- x |> 
      adventdrob:::adjacent_join(diagonal = TRUE) |> 
      group_by(row, col, value, flash, has_flashed) |> 
      summarise(value = first(value) + sum(flash2), .groups = "drop") |> 
      mutate(flash = value > 9 & !has_flashed) |> 
      mutate(has_flashed = flash | has_flashed)
    
    # Part 2
    if (all(x$has_flashed | x$flash)) {
      stop(paste0("All flashed at step ", i))
    }
  }
  # re-initialize Octopuses
  x <- x |> 
    mutate(value = if_else(has_flashed, 0, value))
  
  x_anim <- bind_rows(x_anim, mutate(x, step = i))
}
  
part1

x_anim
```

### Animation

```{r}
library(gganimate)
library(paletteer)

blues <- paletteer_d("colorBlindness::LightBlue2DarkBlue10Steps", n = 9)

pal <- c("gold", blues)

x_anim |> 
  select(-contains("flash")) |>
  filter(step < 51) |> 
  ggplot(aes(x = row, y = col, group = step, colour = factor(value))) +
  geom_point(shape = 15, size = 18) +
  theme_void() +
  transition_states(step, state_length = 4, transition_length = 2) +
  #facet_wrap(~ step) +
  scale_colour_manual(values = pal, guide = "none") +
  labs(title = "Step {closest_state}")  -> octo_flash
anim <- animate(octo_flash, n = 300)
anim
#anim_save(animation = anim, filename =  "octo_flash.gif")
```

