---
title: '14'
author: "A. Ginolhac"
date: "2021-12-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
deter_dice <- function(start) {
  reduce(seq(start, start + 2), `+`)
}

deter_dice(1)

circle <- rep(1:10, 100000)

board <- function(start, roll) {
  circle[start + roll]
}

board(8, 15)
```

Player 1 starting position: 6
Player 2 starting position: 10

```{r}
score1 <- 0
score2 <- 0
start_dice <- 1
start_one <- 6
start_two <- 10
counter <- 0

while (TRUE) {
  if (counter %% 2 == 0) {
    # Player1
    message("score1: ", score1, " pos: ", start_one, " dice: ", 
            deter_dice(start_dice), " board: ",
            board(start_one, deter_dice(start_dice)))
    start_one <- board(start_one, deter_dice(start_dice))
    score1 <- score1 + start_one
    counter <- counter + 1
    if (score1 >= 1000) break
    
  } else {
    # Player 2
    message("score2: ", score2, " pos: ", start_two, " dice: ", 
            deter_dice(start_dice), " board: ",
            board(start_two, deter_dice(start_dice)))
    start_two <- board(start_two, deter_dice(start_dice))
    score2 <- score2 + start_two
    counter <- counter + 1
    if (score2 >= 1000) break
  }
  start_dice <- start_dice + 3
}
counter * 3

```

- Using David Robinson [solution](https://twitter.com/drob/status/1473332179132461061?s=20)

```{r}
starting_position <- c(6, 10)

crossing(turn = 1:1000,
         player = 1:2,
         within_turn = 1:3) |> 
  mutate(roll = rep(1:100, 60)) |> 
  group_by(turn, player) |> 
  summarise(roll = sum(roll)) |> 
  group_by(player) |> 
  mutate(position = (starting_position[1] + cumsum(roll) - 1) %% 10 + 1,
         score = cumsum(position)) |> 
  ungroup() |> 
  #mutate(cumsum(score >= 1000))
  filter(cumsum(score >= 1000) == 0) |> 
  summarise(answer = last(score) * (n() + 1) * 3)
```

incorrect
